name: 'Send notification'
description: 'Send notification'
inputs:
  url:
    description: ''
    required: true
  message:
    description: ''
    required: true
outputs:
  my-output:
    description: ''
runs:
  using: 'node20'
  main: './src/notify.js'